openapi: 3.0.0
info: 
  title: User API
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                email:
                  type: string
                password: 
                  type:string
                required:
                  - email
                  - password
      responses:
              '200':
                description: Login successful
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        email:
                          type: string
                        message:
                          type: string
              '401':
                description: Invalid credentials

  /api/auth/register:
    post:
      summary: Register new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
                name:
                  type: string
                age:
                  type: integer
                  minimum: 18
                gender:
                  type: string
                  enum:
                    - MALE
                    - FEMALE
                role:
                  type: string
                  enum:
                    - volunteer
                    - associationOwner
                country:
                  type: string
                city:
                  type: string
                profilePicture:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '500':
          description: Server error


  /api/upload:
    post:
      summary: Upload an image file
      description: Uploads an image (jpg, png, etc.) with file validation and size limit (2MB).
      tags:
        - File
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: image/png, image/jpeg
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded
                  filename:
                    type: string
                    example: 1718123456789-123456789.jpg
                  path:
                    type: string
                    example: uploads/1718123456789-123456789.jpg
        '400':
          description: Invalid file or request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Only image files are allowed!

  /api/auth/google:
    get:
      tags:
        - Auth
      summary: Start Google OAuth Login/Register
      description: Redirects the user to Google's OAuth 2.0 consent screen.
      responses:
        '302':
          description: Redirects to Google OAuth login page.

  /api/auth/google/callback:
    get:
      tags:
        - Auth
      summary: Google OAuth Callback
      description: Handles Google's OAuth redirect and issues a JWT if successful.
      responses:
        '200':
          description: Successfully authenticated, returns a token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Google login successful
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6...
        '403':
          description: Invalid or expired Google token.
        '500':
          description: Internal server error.

  /api/plan/create:
    post:
      summary: Create a new plan
      tags:
        - Plan
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: My Awesome Plan
                description:
                  type: string
                  example: This is a description of my awesome plan.
                startDate:
                  type: string
                  format: date-time
                  example: 2025-01-15T10:00:00.000Z
                endDate:
                  type: string
                  format: date-time
                  example: 2025-01-20T18:00:00.000Z
                volunteerNumber:
                  type: integer
                  example: 10
                destinationId:
                  type: string
                  example: 550e8400-e29b-41d4-a716-446655440000
                category_id:
                  type: string
                  example: 123e4567-e89b-12d3-a456-426614174000
                fees:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        example: fee-type-1
                      name:
                        type: string
                        example: Registration Fee
                      fees:
                        type: string
                        example: "100.00"
              required:
                - name
                - description
                - startDate
                - endDate
                - volunteerNumber
                - destinationId
                - category_id
                - fees
      responses:
        '201':
          description: Plan created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Plan created successfully
                  data:
                    type: object
        '400':
          description: Validation failed
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Validation failed
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        validation:
                          type: string
                        code:
                          type: string
                        message:
                          type: string
                        path:
                          type: array
                          items:
                            type: string
