openapi: 3.0.0
info: 
  title: User API
  version: 1.0.0
paths:
  /auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                email:
                  type: string
                password: 
                  type:string
                required:
                  - email
                  - password
      responses:
              '200':
                description: Login successful
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        token:
                          type: string
              '401':
                description: Invalid credentials

  /users:
    post:
      summary: Register new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '500':
          description: Server error


  /upload:
    post:
      summary: Upload an image file
      description: Uploads an image (jpg, png, etc.) with file validation and size limit (2MB).
      tags:
        - File
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: image/png, image/jpeg
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded
                  filename:
                    type: string
                    example: 1718123456789-123456789.jpg
                  path:
                    type: string
                    example: uploads/1718123456789-123456789.jpg
        '400':
          description: Invalid file or request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Only image files are allowed!

