openapi: 3.0.0
info: 
  title: User API
  version: 1.0.0
paths:
  /api/auth/login:
    post:
      summary: Login user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema: 
              type: object
              properties:
                email:
                  type: string
                password: 
                  type:string
                required:
                  - email
                  - password
      responses:
              '200':
                description: Login successful
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        email:
                          type: string
                        message:
                          type: string
              '401':
                description: Invalid credentials

  /api/users:
    post:
      summary: Register new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
              required:
                - email
                - password
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  email:
                    type: string
        '500':
          description: Server error


  /api/upload:
    post:
      summary: Upload an image file
      description: Uploads an image (jpg, png, etc.) with file validation and size limit (2MB).
      tags:
        - File
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
            encoding:
              file:
                contentType: image/png, image/jpeg
      responses:
        '200':
          description: File uploaded successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: File uploaded
                  filename:
                    type: string
                    example: 1718123456789-123456789.jpg
                  path:
                    type: string
                    example: uploads/1718123456789-123456789.jpg
        '400':
          description: Invalid file or request
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Only image files are allowed!

  /api/auth/google:
    get:
      tags:
        - Auth
      summary: Start Google OAuth Login/Register
      description: Redirects the user to Google's OAuth 2.0 consent screen.
      responses:
        '302':
          description: Redirects to Google OAuth login page.

  /api/auth/google/callback:
    get:
      tags:
        - Auth
      summary: Google OAuth Callback
      description: Handles Google's OAuth redirect and issues a JWT if successful.
      responses:
        '200':
          description: Successfully authenticated, returns a token.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Google login successful
                  token:
                    type: string
                    example: eyJhbGciOiJIUzI1NiIsInR5cCI6...
        '403':
          description: Invalid or expired Google token.
        '500':
          description: Internal server error.
